# Generated by Django 3.2.12 on 2022-03-09 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='check_in_date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='hotels',
            name='check_out_date',
            field=models.DateField(null=True),
        ),
    ]
