# Generated by Django 3.2.12 on 2022-03-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0002_auto_20220308_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotels',
            name='confirm_no',
            field=models.CharField(auto_created=True, max_length=10, null=True),
        ),
    ]
