# Generated by Django 3.2.12 on 2022-03-09 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0003_hotels_confirm_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hotels',
            name='confirm_no',
        ),
        migrations.AlterField(
            model_name='hotels',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
