# Generated by Django 3.2.12 on 2022-03-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0004_auto_20220308_2339'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookings',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('hotel_name', models.CharField(max_length=200)),
                ('check_in_date', models.DateField(auto_now=True)),
                ('check_out_date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='check_in_date',
        ),
        migrations.RemoveField(
            model_name='hotels',
            name='check_out_date',
        ),
    ]
