# Generated by Django 3.2.12 on 2022-03-11 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0006_auto_20220309_1523'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='num_of_guests',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookings',
            name='num_of_rooms',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
