# Generated by Django 3.2.12 on 2022-03-11 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0007_auto_20220311_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='guest_name',
            field=models.CharField(default='Gagan', max_length=100),
            preserve_default=False,
        ),
    ]
